version: '3.8'

services:
  redis:
    image: redis:7.4.2
    container_name: redistest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: